### PR TITLE
update routes

### PR DESCRIPTION
**Pull request by imor**
## What kind of change does this PR introduce?

Updates routes in UI

## What is the current behavior?

The route to edit a user's profile is at `/<handle>/edit`.

## What is the new behavior?

The route to edit a user's profile will be at `/<handle>/_/edit`

## Additional context

In current routing, there is an ambiguity between what a route like `/a/b` means. It could be either a package `b` published by user `a` or a page `b` for user `a`. For example `/a/edit` currently takes the user to edit their profile. This also means no user can currently publish a package named `edit`.

Although this change breaks a link, it is unlikely that someone would bookmark their profile edit link. This change future proofs us in adding more "account specific" pages. One of those pages which is imminently needed is a new access tokens page for the CLI login feature which we can add at `/<handle>/_/access_tokens` after this PR merges.

### CODE REVIEW

**Review by olirice — COMMENTED** [review]
deferring to alaister on review ping

**Review by alaister — CHANGES_REQUESTED** [review]
Looking good!

If possible, it would be good to add some redirects for the old routes (so we don't break bookmarks) in `next.config.js`. Due to the ambiguity, they won't be perfect, though 😅

Here's what I'm thinking:

- `/<user_handle>` -> `/users/<user_handle>`
- `/<user_handle>/edit` -> `/users/<user_handle>/edit`
- `/<user_handle>/<package_partial_name>` -> `/packages/<user_handle>/<package_partial_name>`

What do you think?

**Comment by olirice** [comment]
Will organizations get lumped under `/users/` too?

imo the `/<handle>/<package>` pattern is concise, and easy to remember, and similar to GitHub.

Could we disambiguate with a magic `/_/` for any internal routing pages instead?

e.g.
```
/olirice/_/edit`
``` 

which would be different from a package named edit
```
/olirice/edit
```

**Comment by imor** [comment]
> Will organizations get lumped under /users/ too?

Oh I completely forgot about orgs. My current change would have put orgs also under `/users`.

> If possible, it would be good to add some redirects for the old routes 

Again, my change doesn't look good if we need to add redirects. I was overly reliant on what `crates.io` was doing. Let's go with what @olirice has suggested: a `/_/` segment in the middle which removes the ambiguity (the original intent of the PR) and keeps the other structure intact. Sweet and simple.

**Review by alaister — APPROVED** [review]
LGTM!

**Pull request merged**
